# Generated by Django 5.1.2 on 2025-03-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de la cita médica')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad de atención')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección postal del lugar de atención')),
                ('fecha', models.DateField(verbose_name='Hora en formato yyyy-mm-dd')),
                ('hora', models.TimeField(verbose_name='Hora de la cita formato 24H 00:00:00')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.paciente')),
            ],
            options={
                'db_table': 'citas_medicas',
            },
        ),
    ]
